services:
  mindoc:
    image: registry.cn-hangzhou.aliyuncs.com/mindoc-org/mindoc:v2.1
    container_name: mindoc
    restart: unless-stopped
    ports:
      - 8181:8181
    volumes:
      - ./mindoc/conf:/mindoc/conf
      - ./mindoc/static:/mindoc/static
      - ./mindoc/views:/mindoc/views
      - ./mindoc/uploads:/mindoc/uploads
      - ./mindoc/runtime:/mindoc/runtime
      - ./mindoc/database:/mindoc/database
    environment:
      - MINDOC_RUN_MODE=prod
      - MINDOC_DB_ADAPTER=sqlite3
      - MINDOC_DB_DATABASE=./database/mindoc.db
      - MINDOC_CACHE=true
      - MINDOC_CACHE_PROVIDER=file
      - MINDOC_ENABLE_EXPORT=false
      - MINDOC_BASE_URL=
      - MINDOC_CDN_IMG_URL=
      - MINDOC_CDN_CSS_URL=
      - MINDOC_CDN_JS_URL=
